repos:
- repo: https://github.com/berendovychRB/pentagonFast
  hooks:
    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [python]
      args: [--max-line-length=200]

    - id: black
      name: black
      entry: blacke
      language: system
      types: [python]
      args: [--line-length=200, --target-version=py37]

    - id: isort
      name: isort
      entry: isort
      language: system
      types: [python]
