version: '3.7'

services:
  api:
    build: .
    container_name: "pentagon-api-container"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/fastapi
    depends_on:
      - db
      - mongodb

  db:
    image: postgres:12.0-alpine
    container_name: "container-db"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=api
    expose:
      - 5432

  mongodb:
    image: mongo
    container_name: "container-mongodb"
    volumes:
      - mongo_data:/var/lib/mongodb/data/
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
    ports:
      - "27014:27014"

volumes:
  postgres_data:
  mongo_data:
