version: '3.7'

services:
  api:
    build: .
    container_name: "pentagon-api-container"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/fastapi
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    container_name: "container-db"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=api
    #      - POSTGRES_HOST=db
    #      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - 5432
#    ports:
#      - "5432:5432"


volumes:
  postgres_data: